/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasmdl5;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import static tugasmdl5.koneksi.koneksiDB;

/**
 *
 * @author ASUS
 */
public class Frame extends javax.swing.JFrame {
    

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        tampildata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumbeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kembali = new javax.swing.JTextField();
        hitungtotal = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        hitungkbl = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        tunai = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        hapus1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelmenu = new javax.swing.JPanel();
        framemenu = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(414, 400));

        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Barang", "Kode ", "Harga ", "Jumlah beli", "Total harga", "Tunai", "Kembalian"
            }
        ));
        tabeltransaksi.setEnabled(false);
        tabeltransaksi.setShowHorizontalLines(true);
        tabeltransaksi.setShowVerticalLines(true);
        tabeltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeltransaksi);

        jLabel10.setFont(new java.awt.Font("Lucida Handwriting", 1, 45)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("RIWAYAT  PENJUALAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Riwayat Penjualan", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Barang                                       :");

        menu.setBackground(new java.awt.Color(255, 255, 204));
        menu.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 204, 102));
        menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Menu -", "Jus Jeruk", "Jus Jambu", "Jus Mangga", "Jus Melon", "Jus Sirsak", "Jus Alpukat" }));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Kode Barang                             :");

        kode.setBackground(new java.awt.Color(255, 255, 204));
        kode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kode.setPreferredSize(new java.awt.Dimension(96, 35));
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Harga Barang                           :");

        harga.setBackground(new java.awt.Color(255, 255, 204));
        harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        harga.setPreferredSize(new java.awt.Dimension(70, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Jumlah Beli                                :");

        jumbeli.setBackground(new java.awt.Color(255, 255, 204));
        jumbeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Total Harga                               :");

        totalharga.setBackground(new java.awt.Color(255, 255, 204));
        totalharga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhargaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Tunai                                          :");

        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Kembalian                                 :");

        kembali.setBackground(new java.awt.Color(255, 255, 204));
        kembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hitungtotal.setBackground(new java.awt.Color(0, 0, 0));
        hitungtotal.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        hitungtotal.setForeground(new java.awt.Color(255, 255, 204));
        hitungtotal.setText("Hitung");
        hitungtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungtotalActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 204));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        hitungkbl.setBackground(new java.awt.Color(0, 0, 0));
        hitungkbl.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        hitungkbl.setForeground(new java.awt.Color(255, 255, 204));
        hitungkbl.setText("Total");
        hitungkbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungkblActionPerformed(evt);
            }
        });

        simpan.setBackground(new java.awt.Color(0, 0, 0));
        simpan.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 255, 204));
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        tunai.setBackground(new java.awt.Color(255, 255, 204));
        tunai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Barang", "Kode ", "Harga ", "Jumlah beli", "Total harga", "Tunai", "Kembalian"
            }
        ));
        tabel.setEnabled(false);
        tabel.setShowHorizontalLines(true);
        tabel.setShowVerticalLines(true);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        hapus1.setBackground(new java.awt.Color(0, 0, 0));
        hapus1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        hapus1.setForeground(new java.awt.Color(255, 255, 204));
        hapus1.setText("Hapus");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(simpan))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalharga)
                            .addComponent(kembali)
                            .addComponent(jumbeli)
                            .addComponent(tunai)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 235, Short.MAX_VALUE)
                        .addComponent(reset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hitungtotal)
                    .addComponent(hitungkbl))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(hapus1)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitungtotal)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitungkbl)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(reset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(hapus1)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Data penjualan", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        panelmenu.setPreferredSize(new java.awt.Dimension(1330, 130));

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        framemenu.setBackground(new java.awt.Color(0, 0, 0));
        framemenu.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        framemenu.setForeground(new java.awt.Color(255, 255, 204));
        framemenu.setText("Tampilkan Menu");
        framemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                framemenuActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Handwriting", 1, 45)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("INFORMASI MENU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(framemenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(110, 110, 110))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(framemenu)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Informasi Menu", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabeltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltransaksiMouseClicked

    }//GEN-LAST:event_tabeltransaksiMouseClicked

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        String plhmenu = (String)menu.getSelectedItem();
        String kode1;
        String harga1;
        kode1 = "";
        harga1 = "";

        switch(plhmenu){
            case "Jus Jeruk" -> {
                kode1 = "001";
                harga1 = "5000";
            }
            case "Jus Jambu" -> {
                kode1 = "002";
                harga1 = "5000";
            }
            case "Jus Mangga" -> {
                kode1 = "003";
                harga1 = "5000";
            }
            case "Jus Melon" -> {
                kode1 = "004";
                harga1 = "5000";
            }
            case "Jus Sirsak" -> {
                kode1 = "005";
                harga1 = "8000";
            }
            case "Jus Alpukat" -> {
                kode1 = "006";
                harga1 = "8000";
            }
        }
        kode.setText(kode1);
        harga.setText(harga1);
    }//GEN-LAST:event_menuActionPerformed

    private void totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalhargaActionPerformed

    private void hitungtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungtotalActionPerformed
        // TODO add your handling code here:
        if (kode.getText().isEmpty() || harga.getText().isEmpty()|| jumbeli.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Silahkan isi kolom terlebih dahulu");
            return;
        }
        try{
            int jumlah1 = Integer.parseInt(jumbeli.getText());
            int harga1 = Integer.parseInt(harga.getText());
            int bayar = harga1 * jumlah1;
            totalharga.setText(Integer.toString(bayar));
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukkan angka dengan benar");
        }
        
       
    }//GEN-LAST:event_hitungtotalActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        menu.setSelectedIndex(0);
        kode.setText("");
        harga.setText("");
        jumbeli.setText("");
        totalharga.setText("");
        tunai.setText("");
        kembali.setText("");
        simpan.setText("Simpan");
    }//GEN-LAST:event_resetActionPerformed

    private void hitungkblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungkblActionPerformed
        // TODO add your handling code here:
        int totalharga1 = Integer.parseInt(totalharga.getText());
        int tunai1 = Integer.parseInt(tunai.getText());
        int kembalian = tunai1 - totalharga1;

        kembali.setText(Integer.toString(kembalian));
         if(tunai1 <= 0){
            JOptionPane.showMessageDialog(this, "Isi Kolom Dengan Benar");
        }
    }//GEN-LAST:event_hitungkblActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String pilih = (String)menu.getSelectedItem();

        switch(pilih){
            case "Jus Jeruk" -> {
            }
            case "Jus Jambu" -> {
            }
            case "Jus Mangga" -> {
            }
            case "Jus Melon" -> {
            }
            case "Jus Sirsak" -> {
            }
            case "Jus Alpukat" -> {
            }
        }

        try {
            java.sql.Connection conn=koneksiDB();
            try (Statement st = conn.createStatement()) {
                st.executeUpdate("INSERT INTO koneksimdl5 VALUES('" + pilih +
                        "','" + kode.getText() + "','" + harga.getText() +  "','" + jumbeli.getText() +
                        "','" + totalharga.getText() +  "','" + tunai.getText() +  "','" + kembali.getText()
                        + "')");
            }
            tampildata();
            hapus();
            JOptionPane.showMessageDialog(this, "data berhasil disimpan");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "data gagal disimpan" + e.getMessage());
        }
        try {
            java.sql.Connection conn=koneksiDB();
            Statement st = conn.createStatement();
            st.executeUpdate("UPDATE koneksimdl5 SET barang ='"+menu.getSelectedItem()
                +"', harga='"+harga.getText()+"', jumlah='"+jumbeli.getText()
                +"', total='"+totalharga.getText()+"', tunai='"+tunai.getText()
                +"', kembalian='"+kembali.getText()+"' WHERE kode='"+kode.getText()+"'");
            st.close();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            tampildata();
        }catch (Exception t){
            System.out.println(t.getMessage());
        }

    }//GEN-LAST:event_simpanActionPerformed

    private void framemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_framemenuActionPerformed
        // TODO add your handling code here:
        menujual frame1 = new menujual();
        panelmenu.removeAll();
        frame1.setVisible(true);

        panelmenu.add(frame1);
    }//GEN-LAST:event_framemenuActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int baris = tabel.rowAtPoint(evt.getPoint());

        String menu1 = tabel.getValueAt(baris, 0).toString();
        menu.setSelectedItem(menu1);

        String kode1 = tabel.getValueAt(baris, 1).toString();
        kode.setText(kode1);

        String harga1 = tabel.getValueAt(baris, 2).toString();
        harga.setText(harga1);

        String jumlahbeli = tabel.getValueAt(baris, 3).toString();
        jumbeli.setText(jumlahbeli);

        String total = tabel.getValueAt(baris, 4).toString();
        totalharga.setText(total);

        String tunai1 = tabel.getValueAt(baris, 5).toString();
        tunai.setText(tunai1);

        String kembalian1 = tabel.getValueAt(baris, 6).toString();
        kembali.setText(kembalian1);
        simpan.setText("Edit");
    }//GEN-LAST:event_tabelMouseClicked

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn=koneksiDB();
            try (Statement st = conn.createStatement()) {
                st.executeUpdate("DELETE FROM koneksimdl5 WHERE Barang='"+menu.getSelectedItem()+ "' ");
            }
            JOptionPane.showMessageDialog(this, "data berhasil dihapus");
            tampildata();
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "data gagal dihapus" + e.getMessage());
        }
    }//GEN-LAST:event_hapus1ActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton framemenu;
    private javax.swing.JButton hapus1;
    private javax.swing.JTextField harga;
    private javax.swing.JButton hitungkbl;
    private javax.swing.JButton hitungtotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jumbeli;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField kode;
    private javax.swing.JComboBox<String> menu;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabeltransaksi;
    private javax.swing.JTextField totalharga;
    private javax.swing.JTextField tunai;
    // End of variables declaration//GEN-END:variables

    private void tampildata() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Menu");
        tbl.addColumn("Kode");
        tbl.addColumn("Harga");
        tbl.addColumn("Jumlah");
        tbl.addColumn("Total");
        tbl.addColumn("Tunai");
        tbl.addColumn("Kembalian");
        
        tabeltransaksi.setModel(tbl); // tbl_mahasiswa sesuaikan dengan variable pada table
        try {
            java.sql.Connection conn=koneksiDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM koneksimdl5");
            while (rs.next()) {
                tbl.addRow( new Object[] {
                    rs.getString("Barang"),
                    rs.getString("Kode"),
                    rs.getString("Harga"),
                    rs.getString("Jumlah"),
                    rs.getString("Total"),
                    rs.getString("Tunai"),
                    rs.getString("Kembalian")
                });
                tabeltransaksi.setModel(tbl);
                tabel.setModel(tbl);
            }
        } catch (SQLException e) {
        }
    }

    private void hapus() {
        menu.setSelectedIndex(0);
        kode.setText("");
        harga.setText("");
        jumbeli.setText("");
        totalharga.setText(""); 
        tunai.setText("");
        kembali.setText(""); 
    }

    private void reset() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
